### ISSUE TITLE
Cannot install on MacOS with M1 chip

### ISSUE THREAD

**Issue by mgrunbauer** [2kai2kai2/VSCode-Python-Resource-Monitor#10]
Hi, thank you for looking at the installation issue https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/issues/7!

Running the v0.2.2 release under MacOS with an M1 chip (arm64), results in the following error:

```
2023-06-05 16:21:12.043 [error] Activating extension kaih2o.python-resource-monitor failed due to an error:
2023-06-05 16:21:12.043 [error] Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=110 uv=1 armv=8 libc=glibc node=16.17.1 electron=22.5.2
    loaded from: /Users/myuser/.vscode/extensions/kaih2o.python-resource-monitor-0.2.2/node_modules/node-ps-data
```

I've checked the `$extension/node_modules/node-ps-data/prebuilds` directory and I see it now contains builds for `darwin-x64`, `linux-x64` and `win32-x64`.

Would it be possible to also include a build for `darwin-arm64`?

Performing the "manual installation steps" as outlined in https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/issues/7 (referencing a locally build `node-ps-data`) still works as a work-around.

I'm not familiar with github runners, but it might not be possible until [this github roadmap issue] will be picked up.

[this github roadmap issue]: https://github.com/github/roadmap/issues/528

**Comment by 2kai2kai2** [comment]
Unfortunately you are correct that this will not be possible with GitHub Runners until they support Apple Silicon, and I have been unable to get cross-compilation to work successfully.
Hopefully this will be possible soon; I may look into workarounds if not.

**Comment by 2kai2kai2** [comment]
A little update: GitHub now has Apple Silicon runners, _BUT_ unfortunately they are still only on large runners, meaning builds would cost money. Hopefully they will soon introduce standard runners on Apple Silicon.

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by 2kai2kai2** [comment]
Fantastic news: we now have Apple Silicon support. The newly published version should populate soon, so make sure to update your extension.
