### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by ghost** [2kai2kai2/VSCode-Python-Resource-Monitor#18]
Hi, I have installed this on windows and linux computers and it will not launch when i debug python program, can you please advise.
Thank you

**Comment by Fackym** [comment]
I had the same problem and one possible solution is changing the "type" attribute from "debugpy" to "python" in the debug config.
"debugpy" seems to be the new default type, and this extension doesn't support the new type yet.

**Comment by pmullee** [comment]
Same issue here, will not launch. Changing type attribute did not work

**Comment by 2kai2kai2** [comment]
Hi, the `debugpy` issue has been fixed, and we now support both python debugger modes. You should be able to install the latest version of the extension for these fixes.

@pmullee if you are having this issue, maybe try updating both your VS Code installation and your extension. If that does not work, feel free to open a new issue with details regarding your system. Thanks!

**Comment by pmullee** [comment]
> Hi, the `debugpy` issue has been fixed, and we now support both python debugger modes. You should be able to install the latest version of the extension for these fixes.
> 
> @pmullee if you are having this issue, maybe try updating both your VS Code installation and your extension. If that does not work, feel free to open a new issue with details regarding your system. Thanks!

It worked, thank you!
