### ISSUE TITLE
UX (size and visibility)

### ISSUE THREAD

**Issue by Cacti2333** [2kai2kai2/VSCode-Python-Resource-Monitor#21]
Hi, and thanks for the great work.

I'm interested in having this Extention installed and I'd suggest the following features for improving user experience:

1. Make it remember the window size
Currently, it would change its window size randomly and likes to take half of the screen width by default
2. Add a feature to toggle its visibility (Activate/Deactivate) using an icon at the bottom bar, a toggle button on the GUI page or fast commands to trigger in the command palette.

Kind regards

**Comment by 2kai2kai2** [comment]
Hi, this issue has finally been resolved in the latest version v0.3.0. The pane is now a dropdown tab in the debug sidebar menu, which means that you can set it to display anywhere a sidebar view can appear, and vscode should remember it.
