### ISSUE TITLE
Not appearing automatically when debugging

### ISSUE THREAD

**Issue by ffisc** [2kai2kai2/VSCode-Python-Resource-Monitor#27]
The docs state that

> Automatically appears in the debug tab when debugging with python.

This is not happening to me, I see no change at all.

Using VS Code Insiders `1.94.0-insider`
Extension version `v0.3.0`

**Comment by 2kai2kai2** [comment]
Hi, have you checked that there is not a closed dropdown? It should appear at the bottom of the debug tab.
<img width="448" alt="image" src="https://github.com/user-attachments/assets/7c273721-df88-4ec1-bd9f-9bb38b049b63">

**Comment by ffisc** [comment]
Yep indeed that was the case, sorry/thanks
