### ISSUE TITLE
How to use it ??

### ISSUE THREAD

**Issue by aszsz123** [2kai2kai2/VSCode-Python-Resource-Monitor#6]
Hi, I think this is a nice tool, but I don't know how to use it

monitoring screen does not appear on the python debug page.

Are there any other settings required?

**Comment by portlandhodl** [comment]
I am having the same issue, would like some assistance.

**Comment by domedav** [comment]
No clue how to use it, a description of usage would come handy

**Comment by 2kai2kai2** [comment]
Hi, it should automatically launch upon running the Python debugger. An issue was recently resolved with a dependency that caused this not to occur. If you're still having an issue, try reinstalling and it should be fixed. Apologies for not responding earlier.

**Comment by Karol-G** [comment]
Hey @2kai2kai2,

Sadly I have the same issue that it does not open for me. I have already the newest version installed.

Best,
Karol

**Comment by 2kai2kai2** [comment]
> Hey @2kai2kai2,
> 
> Sadly I have the same issue that it does not open for me. I have already the newest version installed.
> 
> Best, Karol
@Karol-G 

Thanks, I've made some changes that should (actually) fix this by forcing some `node-modules` to be packaged with it.

**Comment by Karol-G** [comment]
Thanks! It opens now :)
